postit/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users/',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.home,name='home'),
    path('post/add/',views.add_post,name='add'),
    path('post/update/<slug:slug>/',views.update_post,name='update'),
    path('post/delete/<slug:slug>/',views.delete_post,name='delete'),
    path('post/<slug:slug>/',views.detail,name='detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.signin,name='login'),
    path('logout/',views.signout,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/update/',views.update_profile,name='update_profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class CustomUser(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=11,blank=True,null=True)
    address = models.CharField(max_length=50,blank=True,null=True)
    bio = models.TextField(blank=True,null=True)
    occupation = models.CharField(max_length=50,blank=True,null=True)
    profile_pic = models.ImageField(upload_to='profileimg',blank=True,null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.email

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

class RegisterForm(UserCreationForm):
    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email Address'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Username'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Password'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control','placeholder':'Repeat Password'}))

    class Meta:
        model = get_user_model()
        fields = ['email','username','password1','password2']


class UpdateProfileForm(forms.ModelForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'First Name'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Last Name'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'User Name'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'class':'form-control','placeholder':'Email Address'}))
    address = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Your Address'}))
    bio = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control','placeholder':'Your Bio'}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Phone Number'}))
    occupation = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control','placeholder':'Occupation'}))
    profile_pic = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control','placeholder':'Upload Profile Pic'}))

    class Meta:
        model = get_user_model()
        fields = ['first_name','last_name','username','email','address','phone','occupation','bio','profile_pic']

users/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required
from .forms import RegisterForm,UpdateProfileForm
from posts.models import Post

# Create your views here.

def register(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request,'Account created successfully')
            return redirect('posts:home')
    
    context = {'form':form}
    return render(request,'users/register.html',context)


def signin(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request,email=email,password=password)
        if user is not None:
            login(request,user)
            messages.success(request,'You are now logged in!')
            goto = request.GET.get('next')
            if goto:
                return redirect(goto)
            return redirect('posts:home')
        else:
            messages.error(request,'Invalid username or password')
            return redirect('users:login')
        
    return render(request,'users/login.html')


@login_required(login_url='users:login')
def signout(request):
    logout(request)
    messages.error(request,'You are now logged out')
    return redirect('users:login')


@login_required(login_url='users:login')
def profile(request):
    user = request.user
    posts = Post.objects.filter(user=user)
    context = {'user':user,'posts':posts}
    return render(request,'users/profile.html',context)


@login_required(login_url='users:login')
def update_profile(request):
    if request.user.is_authenticated:
        user = request.user
        form  = UpdateProfileForm(instance=user)
        if request.method == 'POST':
            form = UpdateProfileForm(request.POST,request.FILES,instance=user)
            if form.is_valid():
                form.save()
                messages.success(request,'Profile Updated Successfully!')
                return redirect('users:profile')

        context = {'form':form}
        return render(request,'users/update_profile.html',context)
    return redirect('users:login')

users/templates/users/login.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <!-- slider Area Start-->
      <div class="slider-area ">
         <!-- Mobile Menu -->
         <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/Industries_hero.jpg' %}">
             <div class="container">
                 <div class="row">
                     <div class="col-xl-12">
                         <div class="hero-cap text-center">
                             <h2>Login to your Account</h2>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <!-- slider Area End-->
    
    <div style="background:#ff656a" class="d-flex justify-content-center">
        <form action="" method="post" class="form-contact comment_form p-5 bg-dark mb-5 mt-5">
            {% csrf_token %}
            <div class="form-group mb-3 mt-4">
                <input class="form-control" name="email" type="email" placeholder="Email Address">
            </div>
            <div class="form-group mb-3 mt-4">
                <input class="form-control" name="password" type="password" placeholder="Password">
            </div>
            <div class="form-group mt-4">
                <button type="submit" class="col-12 button button-contactForm btn_1 boxed-btn">Login</button>
            </div>
            <p>Don't have an account? <a href="{% url 'users:register' %}">Register</a></p>
        </form>
    </div>

{% endblock content %}

users/templates/users/profile.html
{% extends "layout.html" %}
{% load static %}

{% block content %}

    <main>
        <!-- Team-profile Start -->
        <div class="team-profile py-5">
            <div class="container bg-outline-dark pt-4">
                {% if delete %}
                    <div class="row mb-5 alert alert-danger">
                        <div class="col-12">
                            <p class="text-center p-4">Are you sure you want to delete the post "<strong>{{ post.title }}</strong>"?</p>
                            <form action="" method="post">
                                {% csrf_token %}
                                <div class="text-center">
                                    <button class="btn btn-danger">Yes</button> 
                                    <a href="{% url 'users:profile' %}" class="btn" style="background-color:rgb(54, 52, 52)">No</a>
                                </div>
                            </form>
                        </div>
                    </div>
                {% endif %}
                <div class="row p-2 mb-4">
                    <div class="col-xl-4 col-lg-4 col-md-6">
                        <div class="single-profile">
                            <!-- Front -->
                            <div class="single-profile-front pb-5" style="border:1px solid #ff656a;">
                                <div class="profile-img text-center pt-4">
                                    {% if user.profile_pic %}
                                        <img style="width:250px;height:250px;border-radius:50%;" class="img-fluid img-thumbnail" src="{{ user.profile_pic.url }}" alt="">
                                    {% else %}
                                        <img style="width:250px;height:250px;border-radius:50%;" class="img-fluid img-thumbnail" src="{% static 'assets/img/avatar.png' %}" alt="">
                                    {% endif %}
                                </div>
                                <div class="profile-caption text-center">
                                    <h4><a href="#">{{ user.first_name }} {{ user.last_name }}</a></h4>
                                    <p>
                                        {{ user.occupation }} <br>
                                        <small>{{ user.address }}</small>
                                    </p>
                                </div>
                                <div class="text-center pb-3">
                                    <a href="#" class="btn header-btn">Follow</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-8 col-lg-8 col-md-6">
                        <div class="single-profile">
                            <!-- Back -->
                            <div class="single-profile-back-last" style="border:none;">
                                <h2 class="mt-3">Profile Details</h2>
                                <table class="table">
                                    <tr>
                                        <th>Username</th>
                                        <td>{{ user.username }}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{ user.email }}</td>
                                    </tr>
                                    <tr>
                                        <th>Phone</th>
                                        <td>{{ user.phone }}</td>
                                    </tr>
                                    <tr>
                                        <th>Address</th>
                                        <td>{{ user.address }}</td>
                                    </tr>
                                    <tr>
                                        <th>Bio</th>
                                        <td>{{ user.bio }}</td>
                                    </tr>
                                </table>
                                <div class="form-group mt-4">
                                    <a href="{% url 'users:update_profile' %}" class="button rounded button-contactForm boxed-btn">Edit Profile</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Team-profile End-->
        <div>
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <div class="single-profile mb-30 mt-4 mb-5">
                            <h2 class="p-5 text-center"><span class="pb-3" style="border-bottom:4px solid #ff656a;">Posts cre</span>ated by you</h2>
                        </div>
                    </div>
                </div>
                <div class="row">
                    {% for post in posts %}
                        <div class="col-md-4">
                            <article class="blog_item">
                                <div class="blog_item_img">
                                    <img height="200" class="card-img rounded-0" src="{{ post.thumbnail.url }}" alt="">
                                    <a href="{% url 'posts:detail' slug=post.slug %}" class="blog_item_date">
                                        <h3>Read More</h3>
                                    </a>
                                </div>

                                <div class="blog_details">
                                    <a class="d-inline-block" href="{% url 'posts:detail' slug=post.slug %}">
                                        <h2>{{ post.title }}</h2>
                                    </a>
                                    <p>{{ post.content|safe|truncatechars:'100' }}</p>
                                    <ul class="blog-info-link">
                                        <li><a href="{% url 'posts:update' slug=post.slug %}"><i class="fa fa-edit"></i> Update</a></li>
                                        <li><a href="{% url 'posts:delete' slug=post.slug %}"><i class="fa fa-trash"></i> Delete</a></li>
                                    </ul>
                                </div>
                            </article>
                        </div>
                    {% empty %}
                        <div class="col-12 text-center pb-5">
                            <h5 class="">You have'nt added any post yet.</h5>
                            <a href="{% url 'posts:add' %}" class="btn">Add A Post Now</a>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>

    </main>

{% endblock content %}

users/templates/users/register.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <!-- slider Area Start-->
      <div class="slider-area ">
         <!-- Mobile Menu -->
         <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/Industries_hero.jpg' %}">
             <div class="container">
                 <div class="row">
                     <div class="col-xl-12">
                         <div class="hero-cap text-center">
                             <h2>Get An Account</h2>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <!-- slider Area End-->
    
    <div style="background:#ff656a" class="d-flex justify-content-center">
        <form action="" method="post" class="form-contact comment_form p-5 bg-dark mb-5 mt-5">
            {% csrf_token %}
            {% for field in form %}
                <div class="mb-3 mt-4">
                    <p>{{ field }}</p>
                    {% if field.errors %}
                        <small style="color:#ff656a">{{ field.errors }}</small>
                    {% endif %}
                </div>
            {% endfor %}
            <div class="form-group mt-4">
                <button type="submit" class="col-12 button button-contactForm btn_1 boxed-btn">Register</button>
            </div>
            <p>Already have an account? <a href="{% url 'users:login' %}">Login</a></p>
        </form>
    </div>

{% endblock content %}

users/templates/users/update_profile.html
{% extends "layout.html" %}
{% load static %}

{% block content %}
    <!-- slider Area Start-->
      <div class="slider-area ">
         <!-- Mobile Menu -->
         <div class="single-slider slider-height2 d-flex align-items-center" data-background="{% static 'assets/img/hero/Industries_hero.jpg' %}">
             <div class="container">
                 <div class="row">
                     <div class="col-xl-12">
                         <div class="hero-cap text-center">
                             <h2>Get your profile updated</h2>
                         </div>
                     </div>
                 </div>
             </div>
         </div>
     </div>
     <!-- slider Area End-->

    <div class="row request-back-area section-padding30">
        <div class="col-md-6 offset-md-3">
            <form action="" method="post" enctype="multipart/form-data" class="form-contact contact_form p-5" style="background-color: black;">
                {% csrf_token %}

                <div class="row">
                    {% for field in form %}
                        <div class="col-md-6">
                            <div class="mb-3">
                                <p>{{ field }}</p>
                                {% if field.errors %}
                                    <small style="color:#ff656a">{{ field.errors }}</small>
                                {% endif %}
                            </div>
                        </div>
                    {% endfor %}
                </div>

                <div class="form-group mt-3">
                    <button type="submit" class="button col-12 btn header-btn">Update Profile</button>
                </div>
                <div class="form-group mt-3">
                    <a href="{% url 'users:profile' %}" class="button rounded col-12 button-contactForm boxed-btn">Cancel</a>
                </div>
            </form>
        </div>
    </div>

{% endblock content %}