postit/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users/',include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('',views.home,name='home'),
    path('post/add/',views.add_post,name='add'),
    path('post/update/<slug:slug>/',views.update_post,name='update'),
    path('post/delete/<slug:slug>/',views.delete_post,name='delete'),
    path('post/<slug:slug>/',views.detail,name='detail'),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/',views.register,name='register'),
    path('login/',views.signin,name='login'),
    path('logout/',views.signout,name='logout'),
    path('profile/',views.profile,name='profile'),
    path('profile/update/',views.update_profile,name='update_profile'),
]

templates/layout.html
<!doctype html>
{% load static %}
<html class="no-js" lang="zxx">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>PostWall </title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="manifest" href="site.webmanifest">

		<!-- CSS here -->
            <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/flaticon.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/slicknav.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/magnific-popup.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.min.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/themify-icons.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/slick.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/nice-select.css' %}">
            <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
   </head>

   <body>
       
    <!-- Preloader Start -->
    <div id="preloader-active">
        <div class="preloader d-flex align-items-center justify-content-center">
            <div class="preloader-inner position-relative">
                <div class="preloader-circle"></div>
                <div class="preloader-img pere-text">
                    <span>PostWall</span>
                </div>
            </div>
        </div>
    </div>
    <!-- Preloader Start -->

    <header>
        <!-- Header Start -->
       <div class="header-area">
            <div class="main-header ">
                <div class="header-top top-bg d-none d-lg-block">
                   <div class="container-fluid">
                       <div class="col-xl-12">
                            
                       </div>
                   </div>
                </div>
               <div class="header-bottom  header-sticky">
                    <div class="container-fluid">
                        <div class="row align-items-center">
                            <!-- Logo -->
                            <div class="col-xl-2 col-lg-1 col-md-1">
                                <div class="logo">
                                  <a href="{% url 'posts:home' %}">
                                    <h2><i class="fa fa-globe"></i> PostWall</h2>
                                  </a>
                                </div>
                            </div>
                            <div class="col-xl-8 col-lg-8 col-md-8">
                                <!-- Main-menu -->
                                <div class="main-menu f-right d-none d-lg-block">
                                    <nav> 
                                        <ul id="navigation">               
                                            {% if request.user.is_authenticated %}
                                                <li>
                                                    <a href="#">Hi, {{ request.user.username }}</a>
                                                    <ul class="submenu">
                                                        <li><a href="{% url 'users:profile' %}">Profile</a></li>
                                                        <li><a href="{% url 'posts:add' %}">Add Post</a></li>
                                                    </ul>
                                                </li>
                                            {% else %}
                                                <li>
                                                    <a></a>
                                                </li>
                                            {% endif %}
                                        </ul>
                                    </nav>
                                </div>
                            </div>             
                            <div class="col-xl-2 col-lg-3 col-md-3">
                                <div class="header-right-btn f-right d-none d-lg-block">
                                    {% if request.user.is_authenticated %}
                                        <form action="{% url 'users:logout' %}" method="post">
                                            {% csrf_token %}
                                            <button class="btn header-btn">Logout</button>
                                        </form>
                                    {% else %}
                                        <a href="{% url 'users:login' %}" class="btn header-btn">Login / Register</a>
                                    {% endif %}
                                </div>
                            </div>
                            <!-- Mobile Menu -->
                            <div class="col-12">
                                <div class="mobile_menu d-block d-lg-none"></div>
                            </div>
                        </div>
                    </div>
               </div>
            </div>
       </div>
        <!-- Header End -->
    </header>

    {% for message in messages %}
        {% if message.tags == 'error' %}
            <div class="alert alert-danger text-center my-2">
                {{ message }}
            </div>
        {% else %}
            <div class="alert alert-{{message.tags}} text-center my-2">
                {{ message }}
            </div>
        {% endif %}
    {% endfor %}

    {% block content %}
    {% endblock content %}
    
   <footer>
       <!-- Footer Start-->
       <!-- footer-bottom aera -->
       <div class="footer-bottom-area footer-bg">
           <div class="container">
               <div class="footer-border">
                    <div class="row d-flex align-items-center">
                        <div class="col-xl-12 ">
                            <div class="footer-copy-right text-center">
                                <p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | <i class="fa fa-globe"></i> PostWall
  <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                            </div>
                        </div>
                    </div>
               </div>
           </div>
       </div>
       <!-- Footer End-->
   </footer>
   
	<!-- JS here -->
	
		<!-- All JS Custom Plugins Link Here here -->
        <script src="{% static 'assets/js/vendor/modernizr-3.5.0.min.js' %}"></script>
		<!-- Jquery, Popper, Bootstrap -->
		<script src="{% static 'assets/js/vendor/jquery-1.12.4.min.js' %}"></script>
        <script src="{% static 'assets/js/popper.min.js' %}"></script>
        <script src="{% static 'assets/js/bootstrap.min.js' %}"></script>
	    <!-- Jquery Mobile Menu -->
        <script src="{% static 'assets/js/jquery.slicknav.min.js' %}"></script>

		<!-- Jquery Slick , Owl-Carousel Plugins -->
        <script src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'assets/js/slick.min.js' %}"></script>
        <!-- Date Picker -->
        <script src="{% static 'assets/js/gijgo.min.js' %}"></script>
		<!-- One Page, Animated-HeadLin -->
        <script src="{% static 'assets/js/wow.min.js' %}"></script>
		<script src="{% static 'assets/js/animated.headline.js' %}"></script>
        <script src="{% static 'assets/js/jquery.magnific-popup.js' %}"></script>

		<!-- Scrollup, nice-select, sticky -->
        <script src="{% static 'assets/js/jquery.scrollUp.min.js' %}"></script>
        <script src="{% static 'assets/js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'assets/js/jquery.sticky.js' %}"></script>
        
        <!-- contact js -->
        <script src="{% static 'assets/js/contact.js' %}"></script>
        <script src="{% static 'assets/js/jquery.form.js' %}"></script>
        <script src="{% static 'assets/js/jquery.validate.min.js' %}"></script>
        <script src="{% static 'assets/js/mail-script.js' %}"></script>
        <script src="{% static 'assets/js/jquery.ajaxchimp.min.js' %}"></script>
        
		<!-- Jquery Plugins, main Jquery -->	
        <script src="{% static 'assets/js/plugins.js' %}"></script>
        <script src="{% static 'assets/js/main.js' %}"></script>
        
    </body>
</html>